### ISSUE TITLE
A few more additional tweaks

### ISSUE THREAD

**Issue by nintyalex** [Ribiveer/SMB-Tweaked#2]
As a big Mario fan, I love your work on modernizing (and customizing) this classic game. I've made some tweaks of my own.
First, I've made it so you can start with five lives (as in most later titles, including the All-Stars and Deluxe versions).
After giving each player three lives at the start of the game:
```
.IF TWEAK_FIVE_LIVES
      inc NumberofLives           ;give each player five lives
      inc NumberofLives
      inc OffScr_NumberofLives
      inc OffScr_NumberofLives
.ENDIF
```
I've also made the SFX for 1-Up Mushrooms more uniform with later titles:
```
HandlePowerUpCollision:
      jsr EraseEnemyObject    ;erase the power-up object
      lda #PowerUpFloatey
      jsr SetupFloateyNumber  ;award 1000 points to player by default
      lda PowerUpType         ;check power-up type
      cmp #$02
      bcc Shroom_Flower_PUp   ;if mushroom or fire flower, branch
      cmp #$03
      beq SetFor1Up           ;if 1-up mushroom, branch
      lda #Sfx_PowerUpGrab
      sta Square2SoundQueue   ;otherwise play the power-up sound,
      lda #$23                ;set star mario invincibility
      sta StarInvincibleTimer ;timer, and load the star mario music
      lda #StarPowerMusic     ;into the area music queue, then leave
      sta AreaMusicQueue
      rts

Shroom_Flower_PUp:
      lda #Sfx_PowerUpGrab
      sta Square2SoundQueue
```
Don't worry, I've tested them both and they fit in fine with everything else.

**Comment by Ribiveer** [comment]
That's neat! Could you open up a pull request perhaps? Also, why did you go for incrementing twice in the first thing, instead of just changing the initial number?
Also, might I ask what exactly the change for the 1-Up mushroom does? From what I can gather, the change made here is that it plays the power-up sound if you grab a star, but otherwise behaves identically. Is that correct?
EDIT: Actually, looking at it closer, I can't deduce any sort of change in behaviour here, besides adding bytes. I could be very wrong, though! It's late and I do not have the time to test it out.

**Comment by nintyalex** [comment]
For the lives part, I did that so it wouldn't have to take the fixed lives tweaks into account.
The 1-Up Mushroom SFX change makes it so the power-up sound doesn't play upon grabbing a 1-Up Mushroom (and thus get interrupted by the 1-Up sound).

**Comment by Ribiveer** [comment]
I made two new commits that add these two tweaks. I did implement them somewhat differently, but they're in!
